name: Lab5 - Deploy InventoryService.MVC

on:
  push:
    branches: [ "lab5" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Restore
        run: dotnet restore InventoryService.MVC/InventoryService.MVC.csproj

      - name: Build
        run: dotnet build InventoryService.MVC/InventoryService.MVC.csproj -c Release --no-restore

      - name: Publish
        run: dotnet publish InventoryService.MVC/InventoryService.MVC.csproj -c Release -o ${{ github.workspace }}\published --no-build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_<PUT_MVC_CLIENTID_SUFFIX_HERE> }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F7A660ABC2FB4A7E9F48B841DDAAC476 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_387E06EF9F64423AB7B5A11C3EF907F5 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "rl-lab5-inventory-mvc-dad4b8g4hheyddft"
          slot-name: "Production"
          package: published
